[workspace]
resolver = "3"
members = ["kernel", "bootloader", "user/hello", "user/child", "user/exec-test", "user/pipe-test", "user/mmap-test", "user/mmap-file-test", "user/shared-mmap-test", "user/signal-test"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true

